version: "3"
services:
  jupyter:
      image: jupyter/minimal-notebook
      environment:
        - JUPYTER_ENABLE_LAB=yes
        - PASSWORD="pistols04"
      ports:
        - "8888:8888"
#python3 -m pip install jupyter