version: "3"
services:
  jupyter:
      image: jupyter/datascience-notebook
      container_name:   jupyter_notebook_x
      # environment:
      #   - JUPYTER_ENABLE_LAB=yes
      #   - PASSWORD="senha"
      #   - ACCESS_TOKEN=sha1:d4c78fe19cb5:0c8f830971d52da9d74b9985a8b87a2b80fc6e6a
      ports:
        - "8888:8888"
      volumes:
        - .:/home/jovyan/work
